/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;
import com.badlogic.gdx.physics.bullet.linearmath.*;
import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Matrix3;
import com.badlogic.gdx.math.Matrix4;

public class btVector3i extends BulletBase {
	private long swigCPtr;
	
	protected btVector3i(final String className, long cPtr, boolean cMemoryOwn) {
		super(className, cPtr, cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	/** Construct a new btVector3i, normally you should not need this constructor it's intended for low-level usage. */ 
	public btVector3i(long cPtr, boolean cMemoryOwn) {
		this("btVector3i", cPtr, cMemoryOwn);
		construct();
	}
	
	@Override
	protected void reset(long cPtr, boolean cMemoryOwn) {
		if (!destroyed)
			destroy();
		super.reset(swigCPtr = cPtr, cMemoryOwn);
	}
	
	public static long getCPtr(btVector3i obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	@Override
	protected void finalize() throws Throwable {
		if (!destroyed)
			destroy();
		super.finalize();
	}

  @Override protected synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CollisionJNI.delete_btVector3i(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

  public void setX(int value) {
    CollisionJNI.btVector3i_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return CollisionJNI.btVector3i_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    CollisionJNI.btVector3i_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return CollisionJNI.btVector3i_y_get(swigCPtr, this);
  }

  public void setZ(int value) {
    CollisionJNI.btVector3i_z_set(swigCPtr, this, value);
  }

  public int getZ() {
    return CollisionJNI.btVector3i_z_get(swigCPtr, this);
  }

  public btVector3i() {
    this(CollisionJNI.new_btVector3i__SWIG_0(), true);
  }

  public btVector3i(int _x, int _y, int _z) {
    this(CollisionJNI.new_btVector3i__SWIG_1(_x, _y, _z), true);
  }

}
