/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;
import com.badlogic.gdx.physics.bullet.linearmath.*;
import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Matrix3;
import com.badlogic.gdx.math.Matrix4;

public class btVoxelCollisionInfo extends BulletBase {
	private long swigCPtr;
	
	protected btVoxelCollisionInfo(final String className, long cPtr, boolean cMemoryOwn) {
		super(className, cPtr, cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	/** Construct a new btVoxelCollisionInfo, normally you should not need this constructor it's intended for low-level usage. */ 
	public btVoxelCollisionInfo(long cPtr, boolean cMemoryOwn) {
		this("btVoxelCollisionInfo", cPtr, cMemoryOwn);
		construct();
	}
	
	@Override
	protected void reset(long cPtr, boolean cMemoryOwn) {
		if (!destroyed)
			destroy();
		super.reset(swigCPtr = cPtr, cMemoryOwn);
	}
	
	public static long getCPtr(btVoxelCollisionInfo obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	@Override
	protected void finalize() throws Throwable {
		if (!destroyed)
			destroy();
		super.finalize();
	}

  @Override protected synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CollisionJNI.delete_btVoxelCollisionInfo(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

  public void setPosition(btVector3i value) {
    CollisionJNI.btVoxelCollisionInfo_position_set(swigCPtr, this, btVector3i.getCPtr(value), value);
  }

  public btVector3i getPosition() {
    long cPtr = CollisionJNI.btVoxelCollisionInfo_position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btVector3i(cPtr, false);
  }

  public void setVoxelTypeId(int value) {
    CollisionJNI.btVoxelCollisionInfo_voxelTypeId_set(swigCPtr, this, value);
  }

  public int getVoxelTypeId() {
    return CollisionJNI.btVoxelCollisionInfo_voxelTypeId_get(swigCPtr, this);
  }

  public void setShapeType(int value) {
    CollisionJNI.btVoxelCollisionInfo_shapeType_set(swigCPtr, this, value);
  }

  public int getShapeType() {
    return CollisionJNI.btVoxelCollisionInfo_shapeType_get(swigCPtr, this);
  }

  public void setAlgorithm(btCollisionAlgorithm value) {
    CollisionJNI.btVoxelCollisionInfo_algorithm_set(swigCPtr, this, btCollisionAlgorithm.getCPtr(value), value);
  }

  public btCollisionAlgorithm getAlgorithm() {
    long cPtr = CollisionJNI.btVoxelCollisionInfo_algorithm_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btCollisionAlgorithm(cPtr, false);
  }

  public btVoxelCollisionInfo() {
    this(CollisionJNI.new_btVoxelCollisionInfo(), true);
  }

}
